In [24]:
!pip install torch

In [1]:
# Tensor

In [2]:
# PYTORCH Library

In [3]:
import torch

In [4]:
import numpy as np

In [5]:
data = torch.tensor([[10,23],[49,59],[23,45]])

In [6]:
type(data)

torch.Tensor

In [7]:
data

tensor([[10, 23],
        [49, 59],
        [23, 45]])

In [8]:
data.shape

torch.Size([3, 2])

In [10]:
data.size()

torch.Size([3, 2])

In [11]:
data.numel()

6

In [12]:
data.dtype

torch.int64

In [13]:
print(data)

tensor([[10, 23],
        [49, 59],
        [23, 45]])


In [14]:
data2 = torch.from_numpy(np.array([4,5,6,8]))

In [15]:
data2

tensor([4, 5, 6, 8], dtype=torch.int32)

In [16]:
torch.rand(3,4)

tensor([[0.0531, 0.4044, 0.5211, 0.2694],
        [0.8868, 0.9564, 0.5326, 0.0792],
        [0.6718, 0.4865, 0.4365, 0.8428]])

In [17]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [19]:
data

tensor([[10, 23],
        [49, 59],
        [23, 45]])

In [21]:
data[0,1]

tensor(23)

In [22]:
data+3

tensor([[13, 26],
        [52, 62],
        [26, 48]])

## Deep Neural Network

In [109]:
import torch
import torchvision
import torchvision.transforms as tx
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
import numpy as np
import torch.nn.functional as F

In [110]:
tx = tx.Compose([tx.ToTensor(), tx.Normalize((0.5,0.5,0.5),(0.5,0.5,0.5))])

In [111]:
train_x = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=tx)
x_train = torch.utils.data.DataLoader(train_x, batch_size=8, shuffle=True,num_workers=1)

Files already downloaded and verified


In [112]:
train_x

Dataset CIFAR10
    Number of datapoints: 50000
    Root location: ./data
    Split: Train
    StandardTransform
Transform: Compose(
               ToTensor()
               Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5))
           )

In [113]:
x_train

In [114]:
test_x = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=tx)
x_test = torch.utils.data.DataLoader(test_x, batch_size=8, num_workers=1)

Files already downloaded and verified


In [115]:
test_x

Dataset CIFAR10
    Number of datapoints: 10000
    Root location: ./data
    Split: Test
    StandardTransform
Transform: Compose(
               ToTensor()
               Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5))
           )

In [116]:
classes = tuple('''airplane										
automobile										
bird										
cat										
deer										
dog										
frog										
horse										
ship										
truck'''.replace('\t','').split('\n'))

In [117]:
classes

('airplane',
 'automobile',
 'bird',
 'cat',
 'deer',
 'dog',
 'frog',
 'horse',
 'ship',
 'truck')

In [118]:
class CreateTorchNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3,6,5)
        self.pool = nn.MaxPool2d(2,2)
        self.conv2 = nn.Conv2d(6,16,5)
        self.sdense1 = nn.Linear(16*5*5, 120)
        self.sdense2 = nn.Linear(120, 90)
        self.sdense3 = nn.Linear(90,10)
    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = torch.flatten(x,1)
        x = F.relu(self.sdense1(x))
        x = F.relu(self.sdense2(x))
        x = self.sdense3(x)
        return x

In [119]:
model = CreateTorchNetwork()

In [120]:
model

CreateTorchNetwork(
  (conv1): Conv2d(3, 6, kernel_size=(5, 5), stride=(1, 1))
  (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (sdense1): Linear(in_features=400, out_features=120, bias=True)
  (sdense2): Linear(in_features=120, out_features=90, bias=True)
  (sdense3): Linear(in_features=90, out_features=10, bias=True)
)

In [121]:
len(list(model.parameters()))

10

In [122]:
loss_func = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.001, momentum=0.9)

In [123]:
for ep in range(5):
    cf = 0
    for i, data in enumerate(x_train,0):
        img, labels = data
        optimizer.zero_grad()
        pred = model(img)
        loss = loss_func(pred,labels)
        loss.backward()
        optimizer.step()
        cf += loss.item()
        if i%1000 == 0:
            print('Epoch:%d, loss: %.3f'%(ep,cf/1000))
            cf = 0
print('Training finished')

Epoch:0, loss: 2.280
Epoch:0, loss: 2284.501
Epoch:0, loss: 2036.618
Epoch:0, loss: 1851.514
Epoch:0, loss: 1678.870
Epoch:0, loss: 1609.221
Epoch:0, loss: 1546.177
Epoch:1, loss: 1.223
Epoch:1, loss: 1481.496
Epoch:1, loss: 1443.718
Epoch:1, loss: 1388.667
Epoch:1, loss: 1382.359
Epoch:1, loss: 1353.762
Epoch:1, loss: 1347.812
Epoch:2, loss: 1.187
Epoch:2, loss: 1278.563
Epoch:2, loss: 1269.491
Epoch:2, loss: 1248.019
Epoch:2, loss: 1227.869
Epoch:2, loss: 1237.900
Epoch:2, loss: 1210.034
Epoch:3, loss: 1.068
Epoch:3, loss: 1166.995
Epoch:3, loss: 1150.815
Epoch:3, loss: 1164.104
Epoch:3, loss: 1146.654
Epoch:3, loss: 1135.681
Epoch:3, loss: 1160.237
Epoch:4, loss: 1.790
Epoch:4, loss: 1077.245
Epoch:4, loss: 1070.419
Epoch:4, loss: 1102.300
Epoch:4, loss: 1092.499
Epoch:4, loss: 1085.784
Epoch:4, loss: 1072.148
Training finished


In [73]:
img.shape

torch.Size([8, 3, 32, 32])

In [74]:
labels

tensor([9, 6, 8, 8, 0, 4, 9, 2])

In [124]:
total = 0
correct = 0
with torch.no_grad():
    for test in x_test:
        img, labels = test
        pred = model(img)
        _,prediction = torch.max(pred,1)
        
        total+= labels.size(0)
        correct+= (prediction==labels).sum().item()
print('Accuracy = {}%'.format((100*correct)/total))

Accuracy = 60.23%


In [125]:
torch.save(model.state_dict(),'my_torch_model.pth')

In [126]:
# Load the saved model
m = CreateTorchNetwork()
m.load_state_dict(torch.load('my_torch_model.pth'))

<All keys matched successfully>

In [127]:
m

CreateTorchNetwork(
  (conv1): Conv2d(3, 6, kernel_size=(5, 5), stride=(1, 1))
  (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (sdense1): Linear(in_features=400, out_features=120, bias=True)
  (sdense2): Linear(in_features=120, out_features=90, bias=True)
  (sdense3): Linear(in_features=90, out_features=10, bias=True)
)

In [128]:
# pred = m(input_imgs)