In [1]:
import numpy as np

### Creating Arrays

1. np.array([])
2. np.arange()
3. np.linspace()
4. np.zeros()
5. np.ones()
6. np.random.rand()
7. np.random.randint()
8. np.random.randn()

In [2]:
a = np.array([])

In [3]:
print(a)

[]


In [4]:
a

array([], dtype=float64)

In [5]:
len(a)

0

In [6]:
sum(a)

0

In [7]:
a.shape

(0,)

In [8]:
a.size

0

In [9]:
a.dtype # detecting the datatype

dtype('float64')

In [10]:
a.astype('int8') # changing the data type

array([], dtype=int8)

In [11]:
a.dtype

dtype('float64')

In [12]:
a.tolist()

[]

In [13]:
type(a)

numpy.ndarray

In [14]:
type(a.tolist())

list

In [15]:
b = np.array([3,4,5,6,7,8])
b

array([3, 4, 5, 6, 7, 8])

In [16]:
b.shape

(6,)

In [17]:
b.size

6

In [18]:
b.dtype

dtype('int32')

In [19]:
c = np.array([[4,5,6,8],[9,3,76,2],[56,76,3,8]])
c

array([[ 4,  5,  6,  8],
       [ 9,  3, 76,  2],
       [56, 76,  3,  8]])

In [20]:
c.shape

(3, 4)

In [21]:
c.size

12

#### data operation

In [22]:
# 1. Accessing Data
# Indexing -> arr[ind] (slicing is available here)
# Subscripting -> arr[row,col,3rd,4th,........nd] (slicing is available here)

In [23]:
b[3]

6

In [24]:
b[:3]

array([3, 4, 5])

In [25]:
c[:2,1:]

array([[ 5,  6,  8],
       [ 3, 76,  2]])

In [26]:
b

array([3, 4, 5, 6, 7, 8])

In [27]:
b[3] = 16

In [28]:
b

array([ 3,  4,  5, 16,  7,  8])

In [29]:
b*3

array([ 9, 12, 15, 48, 21, 24])

In [30]:
c+10

array([[14, 15, 16, 18],
       [19, 13, 86, 12],
       [66, 86, 13, 18]])

In [31]:
c

array([[ 4,  5,  6,  8],
       [ 9,  3, 76,  2],
       [56, 76,  3,  8]])

In [32]:
c.reshape(2,6)

array([[ 4,  5,  6,  8,  9,  3],
       [76,  2, 56, 76,  3,  8]])

In [33]:
c.T # Transpose of matrix

array([[ 4,  9, 56],
       [ 5,  3, 76],
       [ 6, 76,  3],
       [ 8,  2,  8]])

In [34]:
# c[4,0:4] = [9,99,999,199]

In [35]:
np.append(c, [[9,99,999,199]])

array([  4,   5,   6,   8,   9,   3,  76,   2,  56,  76,   3,   8,   9,
        99, 999, 199])

In [36]:
d = np.append(c, [[9,99,999,199]],axis=0)
d

array([[  4,   5,   6,   8],
       [  9,   3,  76,   2],
       [ 56,  76,   3,   8],
       [  9,  99, 999, 199]])

In [37]:
np.append(d,[[11],[411],[311],[121]],axis=1)

array([[  4,   5,   6,   8,  11],
       [  9,   3,  76,   2, 411],
       [ 56,  76,   3,   8, 311],
       [  9,  99, 999, 199, 121]])

#### statistical operation

In [38]:
c

array([[ 4,  5,  6,  8],
       [ 9,  3, 76,  2],
       [56, 76,  3,  8]])

In [39]:
c.sum()

256

In [40]:
c.sum(axis=1)

array([ 23,  90, 143])

In [41]:
c.sum(axis=0)

array([69, 84, 85, 18])

#### mathematics

In [42]:
b

array([ 3,  4,  5, 16,  7,  8])

In [43]:
b.argmax()

3

## Creating Arrays

In [44]:
np.arange(1,20,3) # here we decide the gap; no. of values are automatic

array([ 1,  4,  7, 10, 13, 16, 19])

In [45]:
np.linspace(1,20,10) # here we decide the number of values; then the gap is automatic

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [46]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
np.ones((4,3))*255

array([[255., 255., 255.],
       [255., 255., 255.],
       [255., 255., 255.],
       [255., 255., 255.]])

In [49]:
np.random.random((3,4))

array([[0.57523185, 0.12883005, 0.42200661, 0.38892239],
       [0.75746519, 0.34939372, 0.50383601, 0.66148496],
       [0.20814107, 0.25696548, 0.40611889, 0.02475821]])

In [50]:
k = np.random.randint(10,100,(3,4))
k

array([[56, 72, 58, 75],
       [17, 71, 38, 85],
       [87, 94, 80, 17]])

In [51]:
np.random.randn(3,4)

array([[-0.38959505,  0.09451973, -0.31803736,  0.02455568],
       [ 0.30239937, -0.12211615, -0.17920618, -0.35983006],
       [ 0.2327967 ,  0.84991503, -0.40345507, -1.3695348 ]])

## File Handling

In [52]:
np.save('array_k',k)

In [53]:
m = np.load('array_k.npy')

In [61]:
n = np.load('myfiile.npy')

In [58]:
n

array([[40, 82, 20, 60],
       [53, 67, 16, 56],
       [81, 89, 32, 49]])

In [59]:
m

array([[56, 72, 58, 75],
       [17, 71, 38, 85],
       [87, 94, 80, 17]])

In [68]:
np.savetxt('onefile.csv',k,fmt='%d',delimiter=',',header='A,B,C,D',comments='')

In [72]:
p = np.loadtxt('onefile.csv',dtype=str,delimiter=',')
p

array([['A', 'B', 'C', 'D'],
       ['56', '72', '58', '75'],
       ['17', '71', '38', '85'],
       ['87', '94', '80', '17']], dtype='<U2')